### PR TITLE
Create HTML for login page

### PR DESCRIPTION
**Pull request by kmoua19**

### CODE REVIEW

**Comment by clarkdowner** [comment]
@kmoua92, @samdsherman, @WillStockman13 this request has some conflicts with our db/schema.sql file. This is probably from some updates we made to the file, but does anyone know how to resolve those in order to merge this?

**Comment by samdsherman** [comment]
ker needs to work through the git rebase workflow linked to in the learn. when done properly, it means the only difference between master and your commit is the stuff you changed in your branch.

**Comment by kmoua19** [comment]
Sorry guys. Thought I had done this correct but apparently not. I'll go through that article again and make sure I'm doing it correctly. Will also look into how to resolve merge conflicts

**Comment by kmoua92** [comment]
I think I've fixed the merge conflict. @clarkdowner or @WillStockman13 , please take a quick look at the schema for groups (for which I believe you changed the naming convention) and the join table at the bottom to make sure I chose the correct commit to resolve the conflict.

If everything looks good, please merge. Thank you

**Comment by kmoua92** [comment]
So I realized I have some repeat commits in the commit history even though the changes in those commits are only saved once. This shouldn't have an effect on the merge but it dilutes the quality of our linear commit history so I'd like to prevent it in the future. 

If anyone could help explain why it turned out the way it did (maybe calling 'git pull --rebase' more than once when there isn't a new commit on 'upstream'?), I'd greatly appreciate it. Please comment here or hit up slack

**Comment by kmoua19** [comment]
Closed this because how I resolved the merge conflict resulted in a merge commit and according to Learn, we shouldn't have any merge commits in our commit history. Can issue another pull request for login once we start working on authentication

**Pull request closed without merging**
